function anim (item)
{ 
	var canvas=document.getElementById("animation"),demo=canvas.getContext("2d"),largeur=window.innerWidth-10,hauteur=window.innerHeight-10;canvas.width=largeur;canvas.height=hauteur;var firstText=item.settings.textanim,scrollText=item.settings.message,secondText=item.settings.secondText,spriteAtari=item.settings.sprite;if(1==spriteAtari){var img=new Image;img.src="/resources/atari.svg";var img_x=10,img_y=10}var fondhautimg=new Image;fondhautimg.src="/resources/fond-haut.png";var fondbasimg=new Image;
	fondbasimg.src="/resources/fond-bas.png";var stars=[];function newStar(){return{x:600*Math.random()-300,y:200*Math.random()-100}}for(i=10;300>i;)stars.push(newStar()),i++;function renderStars(){i=100;for(demo.beginPath();200>i;){stars[i].x+=stars[i].x/4;stars[i].y+=stars[i].y/30;var a=stars[i].x+1;var b=stars[i].y+310;demo.moveTo(a,b+2);demo.lineTo(a+8,b);if(0>a||a>largeur||10>b||b>hauteur)stars[i]=newStar();i++}demo.stroke()}var saut=0,debut=0;
	function boucle(){demo.fillRect(0,0,largeur,hauteur);demo.drawImage(fondhautimg,0,0,largeur,100);demo.drawImage(fondbasimg,0,hauteur-100,largeur,100);demo.strokeStyle="#22AAAA";demo.stroke();grd=demo.createLinearGradient(18*Math.cos(saut/42*Math.PI),14,largeur-largeur/4,hauteur/3);grd.addColorStop(0,"#CC7777");grd.addColorStop(.1,"#00FFFF");grd.addColorStop(.3,"#999919");grd.addColorStop(.5,"#559555");grd.addColorStop(.7,"#0000FF");grd.addColorStop(.9,"#559555");grd.addColorStop(1,"#999919");demo.fillStyle=
	grd;demo.font="bold italic 80px Arial";demo.fillText(firstText,largeur/3+360*Math.cos(saut/56*Math.PI),140+largeur/6+101*Math.sin(saut/40*Math.PI));demo.font="bold italic 60px Arial";demo.fillText(secondText,6+largeur/2+120*Math.sin(saut/40*Math.PI),140+largeur/6+60*Math.cos(saut/56*Math.PI));i=0;demo.font="28px Courrier";for(demo.fillStyle="rgb(200,200,200)";i<scrollText.length;){var a=largeur-4*debut+22*i,b=hauteur-30+30*Math.sin((saut+i)/50*Math.PI);demo.fillText(scrollText.charAt(i),a,b);i==scrollText.length-
	1&&0>a&&(debut=0);i++}debut++;1==spriteAtari&&(img_x=largeur/3+100*Math.cos(saut/30*Math.PI)+200*Math.sin(saut/90*Math.PI),img_y=hauteur/3+120*Math.cos(saut/50*Math.PI)+50*Math.sin(saut/40*Math.PI),demo.drawImage(img,img_x,img_y));demo.fillStyle="rgb(0,0,0)";renderStars();saut++}setInterval(boucle,40);

}

